name: CI/CD pipeline

on: 
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]


jobs:
  CI-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
      - name: Install Dependencies
        run: npm install
      - name: Linting
        run: npm run lint
      - name: Run tests
        run: npm run test

  Deployment:
    needs: CI-pipeline
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Deploy
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"