name: CI/CD pipeline

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  CI-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
      - name: Install Dependencies
        run: npm install
      - name: Linting
        run: npm run lint
      - name: Run tests
        run: npm run test